Madeline dev
googleinterns/step44-2020 pull request #29
Opened 2020-07-15 16:43 UTC by mcuozzo19

@Yojairo check JSON format if this is how you need it

2020-07-16 20:31 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +    Datastore datastore = mock(DatastoreService.class);
remove "Datastore" you are reassigning not making a new variable.

2020-07-16 20:31 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
Define the mock results. like you define the mock of datastore. only put the line in this function.

2020-07-16 20:31 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
you should have 3 mocks being made in this function request, response, and results.

2020-07-16 20:39 UTC, mcuozzo19 commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
Okay so now results works but it still says datastore is an unknown variable

2020-07-16 20:54 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
Check my other comment. I believe that will resolve your issue.

2020-07-16 20:57 UTC, mcuozzo19 commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
I removed the "Datastore" and got the same error but I can keep messing with it

2020-07-16 21:04 UTC, mcuozzo19 commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +      when(results.asIterable()).thenReturn(MockDatastoreList);//asiterable return list
It is being declared in MockDataServletTester() constructor so its saying it is unfound in the MockDataServletTest class

2020-07-17 21:55 UTC, PaulLockett commented
Remove the commented out code

2020-07-20 18:43 UTC, PaulLockett commented on website/src/main/java/com/google/sps/servlets/MockDataServlet.java
> +      cntr++;
What is this counter for?

2020-07-20 18:44 UTC, PaulLockett commented on website/src/main/java/com/google/sps/servlets/MockDataServlet.java
> +import java. util. Collections;
Be sure to remove any unnecessary imports.

2020-07-20 18:47 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +import static org.mockito.Mockito.atLeast;
Try and remove unnecessary dependencies.

2020-07-20 18:50 UTC, PaulLockett requested changes
Last clean up before merging

2020-07-20 20:11 UTC, PaulLockett commented on website/src/main/java/com/google/sps/servlets/MockDataServlet.java
>  import com.google.appengine.api.datastore.Key;
What are you using Key for?

2020-07-20 20:12 UTC, PaulLockett commented on website/src/test/java/com/google/sps/servlets/MockDataServletTest.java
> +import java. util. Collections;
Where is Collections used in your code?

2020-07-20 20:14 UTC, PaulLockett approved these changes
Nit, some extra dependencies can be removed.

2020-07-20 20:16 UTC, merged